#COMMENT MYSQL

# THIS COMMENT CONTINUES TO THE END OF LINE


-- THIS COMMENT CONTINUES TO THE END OF LINE

/* THIS IS AN IN-LINE COMMENT */

/*
THIS IS A 
MULTIPLE-LINE COMMENT
*/

#EXAMPLE

SELECT * FROM CAR c

CREATE TABLE STACK1 (
/*ID_USER INT,
 * USERNAME VARCHAR(30),
 * PASSWORD VARCHAR(30)
 */
	ID INT
)

#THIS COMMENT WORKS
/*THIS COMMENT WORKS. */
-- THIS COMMENT DOESN'T



#1.2
CREATE TABLE MANAGERIE.BIRD(
	BIRD_ID INT NOT NULL AUTO_INCREMENT,
	SPECIES VARCHAR(300) DEFAULT NULL COMMENT 'YOU CAN INCLUDE GENUS , BUT NEVER SUBSPECIES',
	INDEX IDX_SPECIES (SPECIES) COMMENT 'WE MUST SEARCH ON SPECIES OFTEN',
	PRIMARY KEY(BIRD_ID)
)ENGINE=InnoDB COMMENT 'THIS TABLE WAS INAUGURATED ON FEBUARY 10TH';



