#CREATING DATABASE


# 1 CREATE DATABASE , USERS , AND GRANTS
CREATE DATABASE MYDATABASE_SUB

# IF ALREADY EXISTS 
CREATE DATABASE IF NOT EXISTS MYDATABASE_SUB


#DROP DATABASE 
DROP DATABASE IF EXISTS MYDATABASE_SUB

DROP DATABASE MYDATABASE_SUB


#WE CAN CREATE DATABASE WITH A DEFAULT CHARACTER SET AND COLLATION 
CREATE DATABASE MYDATABASE_SUB CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI

SHOW CREATE DATABASE MYDATABASE_SUB


#SEE YOUR CURRENT DATABASES 
SHOW DATABASES

#SET CURRENT DATABASE 
USE mydatabase

#DEFAULT CHARACTER SET AND COLLATION FOR THE DATABASE 
SELECT @@CHARACTER_SET_DATABASE AS CSET,@@COLLATION_DATABASE AS COL;




#CREATE A USER
CREATE USER 'PRADEEP'@'%' IDENTIFIED BY 'OPENSESAME'

#THE ABOVE CREATES A USER PRADEEP ,ABLE TO CONNECT WITH ANT HOSTNAME DUE TO THE %WILDCARD THE PASSWORD 
#FOR THE USER IS SET TO OPENSESAME WHICH IS HASLED

#CREATE A ANOTHER USER 
CREATE USER 'PRADEEP123'@'%' IDENTIFIED BY 'PASSWORD'


SELECT USER,HOST,PASSWORD FROM MYSQL.USER WHERE USER IN ('PRADEEP','PRADEEP123')


#GRANT
GRANT ALL ON MYDATABASE_SUB.* TO 'PRADEEP'@'%'
GRANT SELECT ON MYDATABASE_SUB.* TO 'PRADEEP123'@'%'

SHOW GRANTS FOR 'PRADEEP'@'%'
SHOW GRANTS FOR 'PRADEEP123'@'%'

#1.2
#CREATING AND SELECTING A DATABASE 

#1.3
#MYDATABASE







