#DELETE

#1.1
#MULTI-TABLE DELETES

CREATE TABLE PEOPLE
(
ID INT PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
GENDER CHAR(1) NOT NULL
)

INSERT PEOPLE (ID,NAME,GENDER) 
VALUES 
(1,'PRADEEP','M'),
(2,'PRA','F'),
(3,'DEEP','F'),
(4,'RADEE','M');


CREATE TABLE PETS
(
ID INT AUTO_INCREMENT PRIMARY KEY,
OWNER_ID INT NOT NULL,
NAME VARCHAR(100) NOT NULL,
COLOR CHAR(100) NOT NULL
)


INSERT PETS (OWNER_ID,NAME,COLOR) 
VALUES 
(1,'ROVER','BEIGE'),
(2,'BUBBLES','PURPLE'),
(3,'SPOT','BLACK AND WHITE'),
(4,'COLOR','WHITE');

SELECT * FROM PEOPLE p 
SELECT * FROM PETS

DELETE P2
FROM PETS P2
WHERE P2.OWNER_ID IN (SELECT P1.ID FROM PEOPLE P1 WHERE P1.NAME='RADEE');





DELETE P2
FROM PEOPLE P1
JOIN PETS P2
ON P2.OWNER_ID = P1.ID 
WHERE P1.NAME = 'DEEP'


DELETE P1 , P2
FROM PEOPLE P1
JOIN PETS P2
ON P2.OWNER_ID = P1.ID 
WHERE P1.NAME = 'PRADEEP'





ALTER TABLE PETS ADD CONSTRAINT `FK_PETS_2_PEOPLE` FOREIGN KEY (OWNER_ID) REFERENCES PEOPLE(ID) ON DELETE CASCADE;

DELETE FROM PEOPLE 
WHERE NAME = 'PRA'


SET FOREIGN_KEY_CHECKS = 0;
DELETE P1 ,P2 FROM PEOPLE P1 JOIN PETS P2 ON P2.OWNER_ID = P1.ID WHERE P1.NAME = 'DEEP';
SET FOREIGN_KEY_CHECKS = 1 ;

#1.2
#DELETE VS TRUNCATE



#1.3
#MULTI-TABLE DELETE
DELETE E
FROM EMPLOYEES E JOIN DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.NAME = 'SALES'

DELETE E,D
FROM EMPLOYEES E JOIN DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE D.NAME = 'SALES'

DELETE 
FROM EMPLOYEES E JOIN DEPARTMENT D  ON E.DAPARTMENTID = D.DEPARTMENTID
WHERE D.NAME = 'SALES'



#1.4
#BASIC DELETE 
DELETE FROM `MYTABLE` WHERE `SOMECOLUMNS` = 'SOMETHING'


#1.5
#DELETE WITH WHERE CLAUSE
DELETE FROM `TABLE_NAME` WHERE `FIELD_ONE` = 'VALUE_ONE'



#1.6
#DELETE ALL ROWS FROM A TABLE 
DELETE FROM TABLE_NAME


#1.7
#LIMITING DELETED
DELETE FROM TABLE_NAME WHERE FIELD_ONE = VALUE_ONE LIMIT 1
















