#1.1
#MISSING GROUP BY TO RETURN UNPREDICTABLE RESULTS : MURPHY'S LAW

SELECT ITEM.ITEM_ID , USES.CATEGORY,COUNT(*) NUMBER_OF_USES
FROM ITEM
JOIN USES ON ITEM.ITEM_ID,USES.ITEM_ID
GROUP BY ITEM.ITEM_ID

#1.2
#MISSING GROUP BY WITH SELECT * , AND HOW TO FIX IT

SELECT ITEM.* , COUNT(*) NUMBER_OF_USES
FROM ITEM
JOIN USES ON ITEM.IREM_ID,USES.ITEM_ID
GROUP BY ITEM.ITEM_ID

SELECT ITEM_ID , COUNT(*) NUMBER_OF_USES
FROM USES
GROUP BY ITEM_ID


SELECT ITEM.* , USECOUNT.NUMBER_OF_USES
FROM ITEM
JOIN (
SELECT ITEM_ID , COUNT(*) NUMBER_OF_USES FROM USES GROUP BY ITEM_ID 
)
USECOUNT ON ITEM.ITEM_ID = USECOUNT.ITEM_ID



#1.3
#ANY_VALUE()

SELECT ITEM.ITEM_ID , ANY_VALUE(USES.TAG) TAG, COUNT(*) NUMBER_OF_USES 
FROM ITEM
JOIN USES ON ITEM.ITEM_ID , USES.ITEM_ID 
GROUP BY ITEM.ITEM_ID







#1.4
#USING AND MISUSING GROUP BY 
SELECT ITEM.ITEM_ID , ITEM.NAME ,COUNT(*) NUMBER_OF_USES
FROM ITEM
JOIN USES ON ITEM.ITEM_ID,USES.ITEM_ID
GROUP BY ITEM.ITEM_ID






SELECT ITEM.ITEM_ID , ITEM.NAME ,COUNT(*) NUMBER_OF_USES
FROM ITEM
JOIN USES ON ITEM.ITEM_ID,USES.ITEM_ID
GROUP BY ITEM.ITEM_ID,ITEM.NAME




