#GROUPBY
#1.1

SELECT DEPARTMENT , COUNT(*) AS "MAN_POWER"
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING COUNT(*) >= 10


#1.2
#GROUP BY USING GROUP COUNT
 
SELECT NAME , GROUP_CONCAT(SCORE ORDER BY SCORE DESC DEPERATOR ' ') AS GRADES
FROM GRADE
GROUP BY NAME


#1.3
#GROUP BY USING MIN FUNCTION 
SELECT DEPARTMENT , MIN(SALARY) AS 'LOWEST SALARY'
FROM EMPLOYEES
GROUP BY DEPARTMENT

#1.4
#GROUP BY WITH AGGREGATE FUNCTIONS


#COUNT()
SELECT CUSTOMER , COUNT(*) AS ORDERS
FROM ORDERS
GROUP BY CUSTOMER
ORDER BY CUSTOMER


#SUM()
SELECT CUSTOMER , SUM(TOTAL) AS ORDERS
FROM ORDERS
GROUP BY CUSTOMER
ORDER BY CUSTOMER

#AVG()
SELECT CUSTOMER , AVG(TOTAL) AS ORDERS
FROM ORDERS
GROUP BY CUSTOMER
ORDER BY CUSTOMER

#MAX
SELECT CUSTOMER , MAX(TOTAL) AS ORDERS
FROM ORDERS
GROUP BY CUSTOMER
ORDER BY CUSTOMER


#MIN
SELECT CUSTOMER , MIN(TOTAL) AS ORDERS
FROM ORDERS
GROUP BY CUSTOMER
ORDER BY CUSTOMER
