#INSERT

#1.1
# INSERT,ON DUPLICATES KEY UPDATE 

INSERT INTO `mytable`
(`INDEX_FIELD`,`OTHER_FIELD_1`,`OTHER_FIELD_2`)
VALUES 
(`INDEX_VALUE`,`INSERT_VALUE`,`OTHER_VALUE`)
ON DUPLICATE KEY UPDATE 
`OTHER_FIELD_1` = `UPDATE_VALUE`,
`OTHER_FIELD_2` = VALUES(`OTHER_FIELD_2`);



#1.2
# INSERTING MULTIPLE ROWS
INSERT INTO `MY_TABLE` (`FIELD_1`,`FIELD_2`) VALUES
(`DATA_1`,`DATA_2`),
(`DATA_1`,`DATA_3`),
(`DATA_1`,`DATA_4`);

SELECT * FROM `PEOPLE`;

INSERT IGNORE INTO `PEOPLE` (`ID`,`NAME`) 
VALUES 
('2','ANNA'),
('2','MIKE');

SELECT * FROM `PEOPLE`;

INSERT INTO `MY_TABLE` VALUES
('DATA_1','DATA_2'),
('DATA_1','DATA_3'),
('DATA_4','DATA_5');

#1.3
#BASIC__INSERT

INSERT INTO `TABLE_NAME` (`FIELD_ONE`,`FIELD_TWO`) VALUES ('VALUE_ONE','VALUE_TWO');

#1.4
#INSERT WITH AUTO_INCREMENT + LAST_INSERT_ID()
CREATE TABLE T (
ID SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
THIS ...,
THAT ...,
PRIMARY KEY (ID)
);


INSERT INTO T (THIS,THAT) VALUES (... , ...);
SELECT LAST_INSERT_ID() INTO @ID ;
INSERT INTO ANOTHER_TABLE (...,T.ID,...) VALUES (... , @ID , ...);




CREATE TABLE IODKU(
ID INT AUTO_INCREMENT NOT NULL,
NAME VARCHAR(99) NOT NULL,
MISC INT NOT NULL,
PRIMARY KEY(ID),
UNIQUE(NAME)
)ENGINE=InnoDB;

INSERT INTO IODKU (NAME,MISC)
VALUES 
('LESLIE',123),
('SALLY',456);

INSERT INTO IODKU (NAME,MISC)
VALUES
('SALLY',3333)
ON DUPLICATE KEY UPDATE 
ID = LAST_INSERT_ID(ID),
MISC = VALUES(MISC);

SELECT LAST_INSERT_ID()

INSERT INTO IODKU (NAME,MISC)
VALUES
('DANA',789)
ON DUPLICATE KEY UPDATE 
ID = LAST_INSERT_ID(ID),
MISC = VALUES(MISC);

SELECT LAST_INSERT_ID()


SELECT * FROM IODKU i 


#1.5
#INSERT SELECT (INSERTING DATAA FROM ANOTHER TABLE)


INSERT INTO `TABLEA` (`FIELD_ONE`,`FIELD_TWO`)
SELECT `TABLEB`.`FIELD_ONE` , `TABLEB`.`FIELD_TWO` 
FROM `TABLEB`
WHERE `TABLEB`.CLMN <> `SOMEVALUE`
ORDER BY `TABLEB`.`SORTING_CLMN`;




#1.6
#LOST AUTO_INCREMENT IDS

CREATE TABLE BURN (
ID SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
NAME VARCHAR (99) NOT NULL,
PRIMARY KEY(ID),
UNIQUE (NAME)
)ENGINE = InnoDB;

INSERT IGNORE INTO BURN (NAME) VALUES ('FIRST'),('SECOND');
SELECT LAST_INSERT_ID() 
SELECT * FROM BURN ORDER BY ID


INSERT IGNORE INTO BURN (NAME) VALUES ('SECOND');
SELECT LAST_INSERT_ID() 
SELECT * FROM BURN ORDER BY ID

INSERT IGNORE INTO BURN (NAME) VALUES ('THIRD');
SELECT LAST_INSERT_ID() 
SELECT * FROM BURN ORDER BY ID


