#ORDERBY

#1.1
SELECT 
..
FROM
..
WHERE
..
GROUP BY
..
HAVING
..
ORDER BY 
..
LIMIT 
..
OFFSET
..

(SELECT ..) UNION (SELECT ..) ORDER BY ...

SELECT ...GROUP_CONCAT(DISTINCT X ORDER BY ... SEPARATOR ...) ...

#PROBABLY USEFUL ONLY FOR MYISAM NOT FOR INNODB
ALTER TABLE ... ORDER BY ... 


#1.2
#BASICS
ORDER BY X

X CAN BE ANY DATATYPE
	


#1.3
#ASCENDING AND DESCENDING

ORDER BY X ABC          --- SAME AS DEFAULT 
ORDER BY X ABC			--- HIGHEST TO LOWEST
ORDER BY LASTNAME , FIRSTNAME -- TYPICAL NAME SORTING : USING TWO COLUMNS 
ORDER BY SUBMIT_DATE DESC -- LATEST FIRST
ORDER BY SUBMIT_DATE DESC , ID ASC  -- LATEST FIRST BUT FULLY SPECFYING ORDER



#1.4
#SOME TRICKS

ORDER BY FIND_IN_SET(CARD_TYPE,"MASTER-CARD,VISA,DISCOVER") -- SORT 'MASTER-CARD' FIRST 

ORDER BY X IS NULL , X -- ORDER BY X,BUT PUT 'NULLS' LAST 

#CUSTOM ORDERING 
SELECT * FROM SOME_TABLE WHERE ID IN (118,17,113,23,72)
ORDER BY FIELD(ID,118,17,113,23,72)






