#UPDATE

#1.1
#UPDATE WITH JOIN PATTERN
UPDATE QUETIONS_MYSQL Q 
JOIN IWTQUESTIONS I 
ON Q.QID = I.QID
SET Q.CLOSEVOTES = I.CLOSEVOTES,
Q.VOTES = I.VOTES,
Q.ANSWERS = I.ANSWERS,
Q.VIEWS = I.VIEWS;


#1.2
#BASIC UPDATE 
#UPDATE A ROWS
UPDATE CUSTOMERS SET EMAIL='PRADEEPRADEE80@GMAIL.COM' WHERE ID = 1


#UPDATE ALL ROWS 
UPDATE CUSTOMERS SET LASTNAME = 'VIRAT'


#1.3
#BULK UPDATE 
UPDATE PEOPLE 
SET NAME = 
(
CASE 
ID 
WHEN 1 THEN 'KAR'
WHEN 2 THEN 'TOM'
WHEN 3 THEN 'MARY'
END 
)
WHERE ID  IN (1,2,3)

#1.4
#UPDATE WITH ORDER BY AND LIMIT
UPDATE [ LOW_PRIORITY ] [ IGNORE ]
TABLE_NAME
SET
COLUMN1 = EXPRESSION1,
COLUMN2 = EXPRESSION2,
...
[WHERE CONDITIONS]
[ORDER BY EXPRESSION [ASC | DESC]]
[LIMIT ROW_COUNT];




#EXAMPLE
UPDATE EMPLOYESS SET ISCONFIRMED = 1 ORDER BY JOININGDATE LIMIT 10

#1.5
#MULTIPLE TABLE UPDATE

UPDATE [LOW_PRIORITY] [IGNORE]
TABLE1, TABLE2, ...
SET 
COLUMN1 = EXPRESSION1,
COLUMN2 = EXPRESSION2,
...
[WHERE CONDITIONS]



UPDATE PRODUCTS , SALESORDERS 
SET
SALESORDERS.QUANTITY = SALESORDERS.QUANTITY - 5,
PRODUCTS.AVAILABLESTOCK = PRODUCTS.AVAILABLESTOCK + 5
WHERE PRODUCTS.PRODUCTID = SALESORDERS.PRODUCTID
AND SALESORDERS.ORDERID = 100 AND SALESORDERS.PRODUCTSID = 20







