/*
CORRELATED SUBQUERY:
						1) A sub query which depends on a value generated by outer query
						2) Here the execution process is as follows
*/

outer query---o/p---> Inner query--->o/p--->|
	^										|
	|										|
	<----------------------------------------

/*

	1)	First Outer query has to be executed and generates some output values
	2)	Second based on these output values, sub query has to be executed
	3)	From subquery we have some output and it is passed to outer query again
	4)	Then outer query has to be executed again.

*/

/*
These sub queries use 2 operators either EXISTS OR NOT EXISTS

EXISTS :
			It returns true if a sub query fetches at least one value. 
			If it  returns TRUE then outer query will display the result.

NOT EXISTS :
			It returns true if a sub query fetches no values at all. 
			If it returns TRUE then outer query will display the result.
	
*/
	
use mydb;


select d.* 
from dept d
where exists(select 10  from emp e where e.dno=d.dno);

select d.* 
from dept d
where not exists(select 10 from emp e where e.dno=d.dno);


select * 
from dept 
where dno=(select dno from emp where eid=4);

#Alternate Query
select d.* from emp e, dept d
where e.eid=4 and e.dno=d.dno;

select * 
from emp 
where dno=(select dno from dept where dname='Finance');

select eid,ename,sal 
from emp 
where dno in(select dno from dept where dname IN ('Productions','Finance'))
ORDER BY SAL;

select * 
from prod_DTLS
where cmpId  IN(select cmpId from comp_dtls  where cmpCountry in('india','usa'));


