/*
CORRELATED SUBQUERY:
						A subquery which depends on a value generated by outer query
*/

#outer query---o/p---> Inner query--->o/p--->|
	^										 |
	|										 |
	<-----------------------------------------


	
use mydb;


#Find The employee in each department who earns more than the average salary in that department

select 
*
from 
emp e1
where sal > (select avg(sal) from emp e2 where e2.dno = e1.dno )


#Find The Department who do not have any employees


/*
These sub queries use 2 operators either EXISTS OR NOT EXISTS

EXISTS :
			It returns true if a sub query fetches at least one value. 
			If it  returns TRUE then outer query will display the result.

NOT EXISTS :
			It returns true if a sub query fetches no values at all. 
			If it returns TRUE then outer query will display the result.
	
*/


SELECT 
*
from 
dept d 
where not exists (select * from emp e where e.dno=d.dno)