/*
CORRELATED SUBQUERY:
						A subquery which depends on a value generated by outer query
*/

#outer query---o/p---> Inner query--->o/p--->|
	^										 |
	|										 |
	<-----------------------------------------

#Note   : When you have to go to Correlation Subquery ?
				
#				When the subquery meets join


#Note	:	Equi-Join will be used in inner query

use mydb;


#Find The employee in each department who earns more than the average salary in that department


# Note : This will not work (SubQuery)

select 
*
from emp e 
where (dno,sal) in (select dno , avg(sal) from emp e where dno is not null group by dno)

# Note : This is correct (Correlation Subquery)

select 
*
from 
emp e1
where sal > (select avg(sal) from emp e2 where e2.dno = e1.dno )


#Alternate Solution in (inline subquery)

select 
a.* 
from emp a
join (select avg(sal) avgsal,dno from emp group by dno) ab 
on ab.dno =a.dno 
where a.sal > ab.avgsal



#Find The Department who do not have any employees


/*
These sub queries use 2 operators either EXISTS OR NOT EXISTS

EXISTS :
			It returns true if a sub query fetches at least one value. 
			If it  returns TRUE then outer query will display the result.

NOT EXISTS :
			It returns true if a sub query fetches no values at all. 
			If it returns TRUE then outer query will display the result.
	
*/


SELECT 
*
from 
dept d 
where exists (select * from emp e)


SELECT 
*
from 
dept d 
where exists (select * from emp e where e.dno=d.dno)

SELECT 
*
from 
dept d 
where not exists (select * from emp e where e.dno=d.dno)



